apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: multi-k8s-homeconvey-com-tls
spec:
    secretName: multi-k8s-homeconvey-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: multi-k8s.homeconvey.com
    dnsNames:
        - multi-k8s.homeconvey.com
        - www.multi-k8s.homeconvey.com
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - multi-k8s.homeconvey.com
                - www.multi-k8s.homeconvey.com
